feat: update to sf cli
hutte-recipes/cicd-incremental-deployment pull request #6
Opened 2023-10-18 20:54 UTC by mmoyaferrer

- Upgrade to `sf` cli
- Changed from `sfdx-cli` to `@salesforce/cli` as `sfdx-cli` is deprecated and this replacement is recommended (https://www.npmjs.com/package/sfdx-cli)

2023-10-19 04:52 UTC, hmayerhutte requested changes

2023-10-19 04:52 UTC, hmayerhutte commented on hutte.yml
> +  sf project deploy start --ignore-conflicts 1>/dev/null
maybe add -w 45 ? 
frequently, our customers forget that, and then run into timeouts during push

2023-10-19 04:52 UTC, hmayerhutte commented on hutte.yml
>  pull_script: |
we have deprecated pull script, for lack of usage/usecases (although I wonder if we might want to bring it back, eg for profile cleanup) - let's remove this at least for now

2023-10-19 18:01 UTC, amtrack approved these changes

2023-10-20 05:17 UTC, hmayerhutte approved these changes

2023-10-21 15:49 UTC, merged